apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      namespace: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myapp:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 2112
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: myapp
  ports:
    - name: "metrics"
      protocol: TCP
      port: 2112
      targetPort: 2112
  type: LoadBalancer
